### ISSUE TITLE
Ja dit kan ik

### ISSUE THREAD

**Issue by njittam** [Area348/Jotihunt#33]

**Comment by Area348** [comment]
Maar nu is de vraag wat kun je allemaal? aan gezien je niet eens een beschrijving hebt gegeven van wat je allemaal kunt :P

**Comment by Area348** [comment]
Krijg je ook een mail/melding als ik iets op git type? of alleen op dit issue? of helemaaaaaal niet....

**Comment by Area348** [comment]
Begrijp dat je geen email krijgt als ik een reactie plaatst ;)
